[pages]
compatibility_date = "2023-06-30"

[build]
command = "cd source && npm install && npx quartz build"
output_directory = "source/public"

[build.environment]
NODE_VERSION = "20"

# Allow the giscus script to run
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://giscus.app; frame-src https://giscus.app; connect-src 'self' https://giscus.app;" 